#
# Copyright 2018-2023 Elyra Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Validate

on: [push, pull_request]

env:
  FORCE_COLOR: true
  NODE_VERSION: 22
  YARN_VERSION: 3.5.0

jobs:
  prepare-yarn-cache:
    name: Prepare Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn ${{ env.YARN_VERSION }}
        run: |
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate
          yarn set version ${{ env.YARN_VERSION }}
          yarn --version
      - name: Install dependencies
        run: |
          yarn install
  lint:
    name: Lint
    needs: prepare-yarn-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn ${{ env.YARN_VERSION }}
        run: |
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate
          yarn set version ${{ env.YARN_VERSION }}
          yarn --version
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Check format
        run: yarn format:check

  test-coverage:
    name: Generate Coverage Report
    needs: prepare-yarn-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn ${{ env.YARN_VERSION }}
        run: |
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate
          yarn set version ${{ env.YARN_VERSION }}
          yarn --version
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Generate coverage report
        run: yarn test:cover
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test:
    name: Test
    needs: prepare-yarn-cache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4 # Install dependencies with latest node version
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn ${{ env.YARN_VERSION }}
        run: |
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate
          yarn set version ${{ env.YARN_VERSION }}
          yarn --version
      - name: Install
        run: yarn install
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

  test-integration:
    name: Run Integration Tests
    needs: prepare-yarn-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn ${{ env.YARN_VERSION }}
        run: |
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate
          yarn set version ${{ env.YARN_VERSION }}
          yarn --version
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Cypress
        run: yarn test:cypress
        env:
          NODE_OPTIONS: --openssl-legacy-provider

  examples:
    name: Build examples
    needs: prepare-yarn-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn ${{ env.YARN_VERSION }}
        run: |
          corepack prepare yarn@${{ env.YARN_VERSION }} --activate
          yarn set version ${{ env.YARN_VERSION }}
          yarn --version
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Install and build examples
        run: |
          cd examples/create-react-app
          yarn install && yarn build
          cd -
          cd  examples/create-react-app-with-typescript
          yarn install && yarn build
